//-----------------------------------------------------------------------
// <copyright company="SomeCompany" file="EventReciver.cs">
// Copyright © 2016
// </copyright>
// <auto-generated />
//-----------------------------------------------------------------------
using Microsoft.SharePoint;
using SuperMarketSystem.Common;
using System;
using System.Runtime.InteropServices;
using System.Linq;

namespace SuperMarketSystem.Features.SuperMarketFeature
{
    /// <summary>
    /// This class handles events raised during feature activation, deactivation, installation, uninstallation, and upgrade.
    /// </summary>
    /// <remarks>
    /// The GUID attached to this class may be used during packaging and should not be modified.
    /// </remarks>
    [Guid("7b50c7cb-da8c-431b-ab65-2a6ca50a584e")]
    public class SuperMarketFeatureEventReceiver : SPFeatureReceiver
    {
        /// <summary>
        /// Occurs after a Feature is activated.
        /// </summary>
        /// <param name="properties">An <see cref="T:Microsoft.SharePoint.SPFeatureReceiverProperties" /> object that represents the properties of the event.</param>
        //public override void FeatureActivated(SPFeatureReceiverProperties properties)
        //{
        //    SPWeb web = SPContext.Current.Web;
        //    web.AllowUnsafeUpdates = true;
        //    bool groupExists = false;

        //    foreach (SPGroup group in web.SiteGroups)
        //    {
        //        if (group.Name == ConfigurationManager.SalesGroup)
        //        {
        //            groupExists = true;
        //            break;
        //        }
        //    }

        //    if (groupExists)
        //    {
        //        SPGroup sales = web.SiteGroups.GetByName(ConfigurationManager.SalesGroup);
        //        SPUserCollection users = sales.Users;
        //        bool isIntheGroup = false;
        //        foreach (SPUser user in users)
        //        {
        //            if (user.LoginName == web.CurrentUser.LoginName)
        //            {
        //                isIntheGroup = true;
        //                break;
        //            }
        //        }
        //        if (!isIntheGroup)
        //        {
        //            sales.Users.Add(web.CurrentUser.LoginName, web.CurrentUser.Email, web.CurrentUser.Name, string.Empty);
        //        }
        //    }
        //    else
        //    {
        //        web.SiteGroups.Add(ConfigurationManager.SalesGroup, web.CurrentUser, web.CurrentUser, string.Empty);
        //    }

        //    web.Update();
        //    web.AllowUnsafeUpdates = false;
        //}

        /// <summary>
        /// Occurs when a Feature is deactivated.
        /// </summary>
        /// <param name="properties">An <see cref="T:Microsoft.SharePoint.SPFeatureReceiverProperties" /> object that represents the properties of the event.</param>
        //public override void FeatureDeactivating(SPFeatureReceiverProperties properties)
        //{
        //    SPWeb web = SPContext.Current.Web;
        //    web.AllowUnsafeUpdates = true;
        //    web.SiteGroups.Remove(ConfigurationManager.SalesGroup);
        //    web.Update();
        //    web.AllowUnsafeUpdates = false;
        //}

        /// Uncomment the method below to handle the event raised after a feature has been installed.
        ///public override void FeatureInstalled(SPFeatureReceiverProperties properties)
        ///{
        ///}

        /// Uncomment the method below to handle the event raised before a feature is uninstalled.
        ///public override void FeatureUninstalling(SPFeatureReceiverProperties properties)
        ///{
        ///}

        /// Uncomment the method below to handle the event raised when a feature is upgrading.
        ///public override void FeatureUpgrading(SPFeatureReceiverProperties properties, string upgradeActionName, System.Collections.Generic.IDictionary<string, string> parameters)
        ///{
        ///}
    }
}
