//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarketSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SupermarketResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupermarketResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperMarketSystem.SupermarketResources", typeof(SupermarketResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null..
        /// </summary>
        public static string ArgumentNullError {
            get {
                return ResourceManager.GetString("ArgumentNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in the authorized user group..
        /// </summary>
        public static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supermarket System.
        /// </summary>
        public static string Catelog {
            get {
                return ResourceManager.GetString("Catelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Query&gt;&lt;Where&gt;&lt;And&gt;&lt;Geq&gt;&lt;FieldRef Name=&apos;InvoiceDate&apos; /&gt;&lt;Value IncludeTimeValue=&apos;TRUE&apos; Type=&apos;DateTime&apos;&gt;{0}&lt;/Value&gt;&lt;/Geq&gt;&lt;Leq&gt;&lt;FieldRef Name=&apos;InvoiceDate&apos; /&gt;&lt;Value IncludeTimeValue=&apos;TRUE&apos; Type=&apos;DateTime&apos;&gt;{1}&lt;/Value&gt;&lt;/Leq&gt;&lt;/And&gt;&lt;/Where&gt;&lt;/Query&gt;.
        /// </summary>
        public static string InvoiceByDateQuery {
            get {
                return ResourceManager.GetString("InvoiceByDateQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice created..
        /// </summary>
        public static string InvoiceCreated {
            get {
                return ResourceManager.GetString("InvoiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the invoice..
        /// </summary>
        public static string InvoiceCreateError {
            get {
                return ResourceManager.GetString("InvoiceCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldRef Name=&apos;InvoiceDate&apos; /&gt;&lt;FieldRef Name=&apos;ID&apos; /&gt;&lt;FieldRef Name=&apos;Total&apos; /&gt;.
        /// </summary>
        public static string InvoiceViewFields {
            get {
                return ResourceManager.GetString("InvoiceViewFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate report exception occurred..
        /// </summary>
        public static string JobError {
            get {
                return ResourceManager.GetString("JobError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV written successfully..
        /// </summary>
        public static string JobFinished {
            get {
                return ResourceManager.GetString("JobFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got invoices....
        /// </summary>
        public static string JobRetrievedInvoices {
            get {
                return ResourceManager.GetString("JobRetrievedInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to execute....
        /// </summary>
        public static string JobStart {
            get {
                return ResourceManager.GetString("JobStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to CSV.
        /// </summary>
        public static string JobWritingDocument {
            get {
                return ResourceManager.GetString("JobWritingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not activate features..
        /// </summary>
        public static string LogFeatureActivateError {
            get {
                return ResourceManager.GetString("LogFeatureActivateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deactivate features..
        /// </summary>
        public static string LogFeatureDeactivateError {
            get {
                return ResourceManager.GetString("LogFeatureDeactivateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to the ULS log:  {0}.
        /// </summary>
        public static string LogFormat {
            get {
                return ResourceManager.GetString("LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}, Stack trace: {1}.
        /// </summary>
        public static string LogMessageStacktrace {
            get {
                return ResourceManager.GetString("LogMessageStacktrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add items to the cart..
        /// </summary>
        public static string MessageAddItem {
            get {
                return ResourceManager.GetString("MessageAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added to cart..
        /// </summary>
        public static string MessageItemAdded {
            get {
                return ResourceManager.GetString("MessageItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no orders..
        /// </summary>
        public static string MessageNoOrders {
            get {
                return ResourceManager.GetString("MessageNoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create order..
        /// </summary>
        public static string OrderCreateError {
            get {
                return ResourceManager.GetString("OrderCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query&gt;&lt;/Query&gt;.
        /// </summary>
        public static string ProductAllQuery {
            get {
                return ResourceManager.GetString("ProductAllQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Where&gt;&lt;Eq&gt;&lt;FieldRef Name=&apos;ID&apos; /&gt;&lt;Value Type=&apos;Number&apos;&gt;{0}&lt;Value&gt;&lt;/Eq&gt;&lt;/Where&gt;.
        /// </summary>
        public static string ProductByIDQuery {
            get {
                return ResourceManager.GetString("ProductByIDQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product item with given ID..
        /// </summary>
        public static string ProductIDNotFound {
            get {
                return ResourceManager.GetString("ProductIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two products cannot have the same ID..
        /// </summary>
        public static string ProductNotUniqeError {
            get {
                return ResourceManager.GetString("ProductNotUniqeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldRef Name=&apos;CategoryName&apos; /&gt;&lt;FieldRef Name=&apos;ID&apos; /&gt;&lt;FieldRef Name=&apos;Price&apos; /&gt;.
        /// </summary>
        public static string ProductViewFileds {
            get {
                return ResourceManager.GetString("ProductViewFileds", resourceCulture);
            }
        }
    }
}
